dist: bionic  # required for Python 3.6
services:
  - xvfb
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
jobs:
  include:
    - env: TOXENV=pylint
before_install:
  - sudo apt-get install -y gir1.2-gtk-3.0 python3-gi-cairo
  - sudo snap install hugo --channel=extended
install:
  - python setup.py build
  - pip install tox-travis
script:
  - tox
notifications:
  email: false
