name: Create Release File

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  upload_archive:
    name: Upload archive
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    steps:
      - run: |
          ref="${{ github.ref_name }}"
          release_name="gnofract4d-${ref#v}"
          echo "release_name=${release_name}" >> $GITHUB_ENV
          echo "release_file=${release_name}.tar.xz" >> $GITHUB_ENV
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: ${{ env.release_name }}
          submodules: recursive
      - name: Install Ubuntu packages
        run: |
          sudo apt update
          sudo apt install hugo
      - name: Save version
        run: >
            echo "${{ github.ref_name }}" > "${{ env.release_name }}"/.gnofract4d_version.txt
      - name: Update help
        working-directory: ${{ env.release_name }}
        run: |
            rm -rf help
            ./createdocs.py
      - name: Remove documentation sources
        working-directory: ${{ env.release_name }}
        run: |
            rm -rf manual website
            rm createdocs.py
      - name: Build archive
        run: >
          tar --exclude=".git*" -cJ "${{ env.release_name }}" -f "${{ env.release_file }}"
      - name: Attest
        uses: actions/attest-build-provenance@v2
        with:
          subject-path: "${{ env.release_file }}"
      - name: Log checksum
        run: >
          sha256sum "${{ env.release_file }}"
      - name: Add file to release
        working-directory: ${{ env.release_name }}
        run: |
          gh release upload "${{ github.ref_name }}" ../"${{ env.release_file }}"
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
